preset: psr12
version: 8
enabled:
  - alpha_ordered_imports
  - binary_operator_spaces
  - blank_line_before_return
  - cast_spaces
  - hash_to_slash_comment
  - heredoc_to_nowdoc
  - include
  - linebreak_after_opening_tag
  - method_separation
  - native_function_casing
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_blank_lines_between_imports
  - no_blank_lines_between_traits
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_spaces_inside_offset
  - no_spaces_outside_offset
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_unneeded_control_parentheses
  - no_unused_imports
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - normalize_index_brace
  - object_operator_without_whitespace
  - phpdoc_add_missing_param_annotation
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_link_to_see
  - phpdoc_no_access
  - phpdoc_no_empty_return
  - phpdoc_no_package
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_single_line_var_spacing
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - print_to_echo
  - short_array_syntax
  - space_after_semicolon
  - standardize_not_equals
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unalign_double_arrow
  - unalign_equals
  - unary_operator_spaces
  - whitespace_after_comma_in_array
