name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.3, 7.4, 8.0, 8.1]
        setup: [basic, stable, lowest]
        exclude:
          - php: 8.0
            setup: lowest
          - php: 8.1
            setup: lowest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}

      - name: Install Composer dependencies
        run: |
          if [[ ${{matrix.setup}} = 'basic' ]]; then composer install --prefer-dist --no-interaction --no-suggest; fi
          if [[ ${{matrix.setup}} = 'stable' ]]; then composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
          if [[ ${{matrix.setup}} = 'lowest' ]]; then composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest --prefer-stable; fi

      - name: Run PHPUnit tests
        run: |
          vendor/bin/phpunit --testdox
